name: Rebase Branch

on:
    create:
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write
    
jobs:
    rebase:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                    fetch-depth: 0

            - name: Set up Git
              run: |
                    git config --global user.name 'github-actions[bot]'
                    git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

            - name: Rebase branch
              run: |
                    git checkout database_update
                    git rebase -Xtheirs origin/master
                    git commit --amend -m "Renamed database columns in payments and order_details table"
                    git push origin database_update --force
              env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
